<?

// Share options

?>

	<div class="container twelve columns">
		<div class="info six columns share">
			<h3>Share
				<a target="_blank" href="http://twitter.com/share?text=Wemakedesign / <?php echo $page->title; ?>&<?php echo $page->url; ?>&via=wemakedesign">Tweet</a>
				<a class="meta_link" target="_blank" href="https://www.facebook.com/sharer.php?u=<?php echo $page->httpUrl; ?>">Like</a>
				<a class="meta_link" target="_blank" href="https://plus.google.com/share?url=<?php echo $page->httpUrl; ?>">G+</a></h3>
		</div>
	</div>

